 <?php $collection = $this->getCollection()->getFirstItem();
 $relations = Webclues_Beautyprofiler_Model_Beutyprofiler::getRelation();
 //print_r($relations);

 //echo "<pre>"; print_r($collection);  exit;
// echo $collection->getFullName();
 ?>
 <div class="panel panel-primary setup-content" id="step-1">
     <h3 class="panel-title">YOUR PERSONAL DETAILS</h3>
     <div class="yur-prfl-lnk">
         <a href="<?php echo $this->getUrl('').
                'beautyprofiler/list/dashboard'; ?>">Your Profiles</a>
     </div>
        <div class="panel-body">
            <div class="form-bx">
                <div class="form-group">
                    <div class="flupd">
                        <div class="input-group">
                        <span class="input-group-btn">
                            <span class="btn btn-default btn-file">

                                <?php  if(!empty($collection->getProfilePicUrl())){
                                    //unlink(Mage::getBaseUrl().'media/beautyprofile/profile/'.$collection->getProfilePicUrl());
                                    $imgUrl = Mage::getBaseUrl().'media/beautyprofile/profile/'.$collection->getProfilePicUrl();
                                }
                                else
                                {
                                    $imgUrl = Mage::getBaseUrl().'media/beautyprofile/profile/noimage.jpg';
                                } ?>

                                 Browse…  <input type="file" name="profile_pic_url" id="imgInp">

                            </span>
                        </span>

                        <div class="img-upld"><img src="<?php echo $imgUrl; ?>" name="profile_pic_url" id="imgInp" class="img_prw"><img id='img-upload'/></div>
                        <input type="text" class="form-control" readonly>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="sz-details">
                        Upload your profile photo here.
                        Recommended size: 500x500 px
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label">Full Name<span class="required"></span></label>
                        <input name="full_name" value="<?php echo $collection->getFullName(); ?>" maxlength="100" type="text" class="form-control required-entry full_name_class" placeholder="Enter Full Name" id="full_name" />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                   <!--  <div class="form-group">
                        <label class="control-label">Email<span class="required">*</span></label>
                        <input maxlength="100" type="text" class="form-control validate-email" id="email" name="email" placeholder="Enter Email" />
                    </div> -->
                </div>
            </div>
            <div class="row">
                    <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label">Please confirm whose Beauty Profile is this ?</label>
                        <div class="form-group">
                            <select name="whose_beautyprofile" class="form-control">
                                <?php foreach($relations as $relation){
                                if($collection->getWhoseBeautyprofile() == $relation){
                                $selected = "selected=selected";      
                                }
                                else
                                {
                                $selected = '';
                                }
                                ?>
                                <option value="<?php echo $relation;?>" <?php echo $selected; ?> ><?php echo ucfirst($relation); ?></option>
                                <?php } ?>         
                            </select>
                        </div>
                        <div style="display:none;color:red;" id="profile_exist"></div>
                    </div>  
                    </div>
            </div>

                    

            <div class="row">
                <div class="col-md-5">
                    <div class="form-group">
                        <label class="control-label def-frm-lable">Date of birth<span class="required"></span></label>
                        <div id="datedropdown">
                        </div>

                       <!--  <div class="col-md-4">
                            <div class="form-group">
                                <select id="Date" name="date[date]" class="selectpicker form-control">
                                    <option>Date</option>
                                    <option>1</option>
                                    <option>2</option>
                                    <option>3</option>
                                    <option>4</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <select id="Month" name="date[month]" class="selectpicker form-control">
                                    <option>Month</option>
                                    <option>1</option>
                                    <option>2</option>
                                    <option>3</option>
                                    <option>4</option>
                                    <option>111</option>
                                    <option>222</option>
                                    <option>33</option>
                                    <option>44</option>
                                    <option>12</option>
                                    <option>25</option>
                                    <option>35</option>
                                    <option>48</option>
                                    <option>178</option>
                                    <option>265</option>
                                    <option>344</option>
                                    <option>40</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <select id="Year" name="date[year]" class="selectpicker form-control">
                                    <option>Year</option>
                                    <option>2017</option>
                                    <option>2016</option>
                                    <option>2015</option>
                                    <option>2014</option>
                                </select>
                            </div>
                        </div> -->
                    </div>
                </div>
            </div>
            <div class="result-text"></div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label">Email<span class="required"></span></label>
                        <input type="text" name="useremail" id="useremail" class="form-control required-entry validate-email" value="<?php echo $collection->getEmail(); ?>"/>
                        <div style="display:none;color:red;" id="already_exist"></div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12 frm-action">
                    <!--<a href="<?php /*echo $this->getUrl('').'beautyprofiler/list'; */?>"> <button class="btn btn-primary backtBtn" type="button">Back</button></a>-->
                    <button class="btn btn-primary nextBtn" id="step1" type="button">CONTINUE</button>
                    <!-- <button class="btn btn-primary nextBtn" type="submit">CONTINUE</button> -->
                </div>
            </div>

        </div>
 </div>
 <script>
     $j(document).ready( function() {
         $j(document).on('change', '.btn-file :file', function() {
             var input = $j(this),
                 label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
             input.trigger('fileselect', [label]);
         });

         $j('.btn-file :file').on('fileselect', function(event, label) {

             var input = $j(this).parents('.input-group').find(':text'),
                 log = label;

             if( input.length ) {
                 input.val(log);
             } else {
                 if( log ) alert(log);
             }

         });
         function readURL(input) {
             if (input.files && input.files[0]) {
                 var reader = new FileReader();

                 reader.onload = function (e) {
                     $j('#img-upload').attr('src', e.target.result);
                 }

                 reader.readAsDataURL(input.files[0]);
             }
         }

         $j("#imgInp").change(function(){
             readURL(this);
         });
         $j('#Date').selectpicker({
             liveSearch: true,
             maxOptions: 1
         });
         $j('#Month').selectpicker({
             liveSearch: true,
             maxOptions: 1
         });
         $j('#Year').selectpicker({
             liveSearch: true,
             maxOptions: 1
         });

     });
 function calculate() {

  /*Validation.add('validate-email', 'Please enter a valid Gmail address. For example johndoe@gmail.com.', function(v) {
    alert(v);
    return Validation.get('IsEmpty').test(v) || /^([a-zA-Z0-9]+[a-zA-Z0-9._%-]*@gmail\.com)$/i.test(v)
})*/
 }
     /*
function calculate() {

  v1 =  Validation.validate($j('email'));
  alert('testtt');
    if(v1) {
            // Callculations & Much More Form Logic is Here
            // Includes a Lot of jQuery
            jQuery('.result-text').html('Your results are:');
        }
        else
        {
            return false;
        }
       // v1 = Validation.validate($('calc-height'));
       // v2 = Validation.validate($('calc-width'));
        /*if(v1) {
            // Callculations & Much More Form Logic is Here
            // Includes a Lot of jQuery
            jQuery('.result-text').html('Your results are:' + results);
             }*/
      /*  }*/
      $j(function() {
          window.dob_val = "<?php echo $collection->getDob(); ?>";

          var dob = dob_val.split(" ");
          var dob1 = dob[0];


                    $j("#datedropdown").dateDropdowns({
                        defaultDateFormat: 'dmy',
                        defaultDate: dob1
                    });
                    $j('input[type="hidden"]').attr('name', 'dob').attr('readonly', 'readonly').attr('class', 'required-entry').attr('id', 'dob_valid');
                });


     $j(document).on('change',"#imgInp",function() {
         $j('.img_prw').hide();
     });

 </script>